### ISSUE TITLE
ValueError: prev block not found

### ISSUE THREAD

**Issue by lpellegr** [QuarkChain/pyquarkchain#164] opened 2018-10-16 16:24 UTC
Using 3 machines, each running a cluster (started with mining enabled) with slaves and shards, when I trigger multiple consecutive load tests, I notice several errors similar to the following in the output:

> SLAVE_S161: E1016 16:20:22.501752 shard.py:532] Traceback (most recent call last):
> SLAVE_S161: File "/home/x/pyquarkchain/quarkchain/cluster/shard.py", line 530, in add_block
> SLAVE_S161: xshard_list = self.state.add_block(block)
> SLAVE_S161: File "/home/x/pyquarkchain/quarkchain/cluster/shard_state.py", line 656, in add_block
> SLAVE_S161: self.__validate_block(block)
> SLAVE_S161: File "/home/x/pyquarkchain/quarkchain/cluster/shard_state.py", line 424, in __validate_block
> SLAVE_S161: block.header.hash_prev_minor_block.hex(),
> SLAVE_S161: ValueError: [161] prev block not found, block height 226 prev hash 256fdd2e28f80a19beda8a7ea285483b708de6f5cf47a1f3b8c52998a12d7d28

**Comment by qcdll** [comment] 2018-10-17 19:08
duplicate of #166

**Closed by qcdll** 2018-10-17 19:08 UTC
Labels: duplicate
