### ISSUE TITLE
Cluster P2P valid peers discovery issue

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#432] opened 2019-03-23 08:26 UTC
Please note, that after hard-seeking, but successful connection to at least 1 peer, the cluster is failing to expand the connections to more peers, here is the status after 3-4 hours of synchronization:

```
Chains:             6
Network Id:         25
Peers:              158.140.159.41:38291

Timestamp             Syncing    ROOT CHAIN/SHARD-HEIGHT
2019-03-23 08:23:29     False   13501 0/0-82289 1/0-75454 2/0-75810 3/0-82625 4/0-83174 4/1-83075 5/0-81658 5/1-81600
```

There is still 1 connected peer and cluster not expanding anymore, which is bad for p2p networking.

**Comment by qcdll** [comment] 2019-03-23 18:39
Thanks for reporting the issue, we were aware of the incident

1. one of the auditing firms that we hired launched an attack on the testnet by sending eth node info to our discovery protocol
2. the eth nodes lead to discovery of more eth nodes (~10K) and they quickly filled routing table of qkc nodes
3. because of the massive amount of valid eth nodes, it is hard to connect to working quarkchain peers

we made a hotfix #429 to blacklist nodes, please pull the code before running the node (you are welcome to try #433 as well). It will still be hard to establish good connection given the routing table is highly polluted, but peer number should stabilize within a few hours

please let us know if this works

**Comment by qcdll** [comment] 2019-03-23 18:41
note that we will change discovery protocol to prevent such attack as well

**Comment by Bambarello** [comment] 2019-03-24 16:23
Thanks for the detailed response, the issue background is clear. I just wanted to note, that I've pulled the up-to-date code from Git, running node for 24+ hours, and node is connected only to 3 peers. Please consider this when updating the code (if applicable):

```
Peers:              158.140.159.42:38291, 68.183.179.34:38291, 54.65.74.78:38291

Timestamp             Syncing    ROOT CHAIN/SHARD-HEIGHT
2019-03-24 16:21:26     False   15534 0/0-94274 1/0-87554 2/0-87804 3/0-94712 4/0-94600 4/1-94468 5/0-93110 5/1-93117
```

**Comment by qcdll** [comment] 2019-03-29 00:15
if there is still trouble connecting, please reboot your cluster. and more fixes are coming forth to provide better connectivity

also, some background to understand the incident: https://github.com/ethereum/devp2p/wiki/Discovery-Overview#capability

**Comment by qcdll** [comment] 2019-03-29 01:40
duplicate of #442

**Closed** 2019-03-29 20:48 UTC
Labels: p2p
