### ISSUE TITLE
Improve transaction queue

### ISSUE THREAD

**Issue by qcgg** [QuarkChain/pyquarkchain#42] opened 2018-08-27 17:52 UTC
The transaction queue `evm/transaction_queue.py` we copied from pyethereum is very basic which doesn't buffer transactions with higher nonces.
py-evm and go-ethereum should have better design that we can borrow.

**Comment by ninjaahhh** [comment] 2019-06-12 20:47
close as duplicate of #552

**Closed by ninjaahhh** 2019-06-12 20:47 UTC
Labels: enhancement
