### ISSUE TITLE
MASTER: E0330 13:32:35.700522 web_protocol.py:310] Error handling request

### ISSUE THREAD

**Issue by Bambarello** [QuarkChain/pyquarkchain#445] opened 2019-03-30 13:41 UTC
Please consider this bug report and fix the code as appropriate:
Node version 2.5.4

```
MASTER: E0330 13:32:35.700522 web_protocol.py:310] Error handling request
MASTER: Traceback (most recent call last):
MASTER: File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_protocol.py", line 381, in start 
MASTER: resp = await self._request_handler(request)
MASTER: File "/usr/local/lib/python3.6/dist-packages/aiohttp/web_app.py", line 322, in _handle
MASTER: resp = await handler(request)
MASTER: File "/code/pyquarkchain/quarkchain/cluster/jsonrpc.py", line 455, in __handle
MASTER: method = d.get("method", "null")
MASTER: AttributeError: 'list' object has no attribute 'get'
```

**Comment by qizhou** [comment] 2019-03-31 14:47
Please provide reproduction steps.

**Comment by Bambarello** [comment] 2019-04-01 07:05
Here is an update.

1) Node was running Ok
2) At some timepoint it's noted, that the node is a few (then +10) root blocks behind other nodes, and looks as it's stucked.
3) Node was stopped
4) Node started with the same blockchain, found bootnodes, found peers, started syncing

Then the error below (in the logs):

```
SLAVE_S3: E0331 18:52:53.908687 shard.py:599] Traceback (most recent call last):
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 597, in add_block
SLAVE_S3: xshard_list, coinbase_amount_map = self.state.add_block(block)
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 842, in add_block
SLAVE_S3: block, gas_limit=gas_limit, xshard_gas_limit=xshard_gas_limit
SLAVE_S3: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 662, in __validate_block
SLAVE_S3: raise ValueError("cannot find root block for the minor block")
SLAVE_S3: ValueError: cannot find root block for the minor block
SLAVE_S3:
SLAVE_S1: E0331 18:52:59.976021 shard.py:599] Traceback (most recent call last):
SLAVE_S1: File "/code/pyquarkchain/quarkchain/cluster/shard.py", line 597, in add_block
SLAVE_S1: xshard_list, coinbase_amount_map = self.state.add_block(block)
SLAVE_S1: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 842, in add_block
SLAVE_S1: block, gas_limit=gas_limit, xshard_gas_limit=xshard_gas_limit
SLAVE_S1: File "/code/pyquarkchain/quarkchain/cluster/shard_state.py", line 577, in __validate_block
SLAVE_S1: block.header.hash_prev_minor_block.hex(),
SLAVE_S1: ValueError: [5/1] prev block not found, block height 153036 prev hash 3a1f3f9b483b16b7330ecb5a4fd89bdbbb6527a81268ec22874d00b3ac05c8aa
```

```
QuarkChain Cluster Stats

Network Id:         25
Peers:              34.223.40.81:38291, 35.184.201.193:38291, 157.230.113.227:38291

Timestamp             Syncing    ROOT CHAIN/SHARD-HEIGHT
2019-03-31 18:51:22      True   25305
2019-03-31 18:51:37      True   25331 0/0-153765 1/0-147707 2/0-148316 3/0-155269 4/0-153949 4/1-153849 5/0-152809 5/1-152838
2019-03-31 18:51:53      True   25356 0/0-153921 1/0-147874 2/0-148475 3/0-155446 4/0-154110 4/1-154011 5/0-152994 5/1-152973
2019-03-31 18:52:08     False   25365 0/0-153971 1/0-147930 2/0-148525 3/0-155509 4/0-154168 4/1-154068 5/0-153058 5/1-153031
2019-03-31 18:52:24     False   25365 0/0-153975 1/0-147930 2/0-148525 3/0-155511 4/0-154169 4/1-154069 5/0-153058 5/1-153033
2019-03-31 18:52:52     False   25365 0/0-153975 1/0-147930 2/0-148525 3/0-155512 4/0-154170 4/1-154070 5/0-153059 5/1-153033
2019-03-31 18:53:07     False   25367 0/0-153981 1/0-147934 2/0-148531 3/0-155521 4/0-154173 4/1-154074 5/0-153062 5/1-153036
2019-03-31 18:53:22     False   25367 0/0-153982 1/0-147935 2/0-148533 3/0-155521 4/0-154175 4/1-154075 5/0-153063 5/1-153037
```

**Comment by Bambarello** [comment] 2019-04-01 11:03
And today - another 2.4.4 node detected the same issue - node became **a little behind** the main chain (root block and all)

Here is the sync status - stuck at 26311 while others are26389

```
2019-04-01 10:57:01     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:57:16     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:57:31     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:57:47     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:58:02     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:58:17      True   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:58:32     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:58:47     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:59:06      True   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:59:21     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:59:36     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 10:59:51     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 11:00:06     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441                                                                                   │····················
2019-04-01 11:00:22     False   26311 0/0-159486 1/0-153359 2/0-154042 3/0-161045 4/0-159525 4/1-159450 5/0-158473 5/1-158441   
```  

and error log:

```
MASTER: RuntimeError: minor block is still unavailable in master after root block sync                                                                                                                          │····················
MASTER:                                                                                                                                                                                                         │····················
MASTER: E0401 10:58:43.060540 peer.py:1066] Closing connection to <Node(0x5eeaae0986bb6d7e36fd3a23ae15ca371ba9e88e8545825ed587a472b5ec417c3f757ee46e643d834a7ff454855cfc28b736b8b76f2eae3ebbe61028b777971c@35.15│····················
5.213.180:38291)>                                                                                                                                                                                               │····················
MASTER: E0401 10:59:09.931638 peer.py:1056] Disconnected during handshake <Node(0x5eeaae0986bb6d7e36fd3a23ae15ca371ba9e88e8545825ed587a472b5ec417c3f757ee46e643d834a7ff454855cfc28b736b8b76f2eae3ebbe61028b77797│····················
1c@35.155.213.180:38291)>: HandshakeDisconnectedFailure('QuarkPeer <Node(0x5eea@35.155.213.180)> disconnected before completing sub-proto handshake: too_many_peers',)                                          │····················
MASTER: E0401 10:59:18.191709 master.py:105] Traceback (most recent call last):                                                                                                                                 │····················
MASTER: File "master.py", line 103, in sync                                                                                                                                                                     │····················
MASTER: await self.__run_sync()                                                                                                                                                                                 │····················
MASTER: File "master.py", line 169, in __run_sync                                                                                                                                                               │····················
MASTER: await self.__add_block(block)                                                                                                                                                                           │····················
MASTER: File "master.py", line 227, in __add_block                                                                                                                                                              │····················
MASTER: await self.__sync_minor_blocks(root_block.minor_block_header_list)                                                                                                                                      │····················
MASTER: File "master.py", line 275, in __sync_minor_blocks                                                                                                                                                      │····················
MASTER: "minor block is still unavailable in master after root block sync"                                                                                                                                      │····················
MASTER: RuntimeError: minor block is still unavailable in master after root block sync                                                                                                                          │····················
MASTER:                                                                                                                                                                                                         │····················
MASTER: E0401 10:59:23.371802 p2p_server.py:172] Could not complete handshake:    

```

**Comment by Bambarello** [comment] 2019-04-01 11:15
And here is also the "warning" log when restarting synchro:

```
MASTER: W0401 11:13:28.385050 master.py:124] [R] abort syncing due to forking at super old block 24016 << 26397                                                                                                 │····················
MASTER: W0401 11:13:28.386141 master.py:124] [R] abort syncing due to forking at super old block 4742 << 26397                                                                                                  │····················
MASTER: W0401 11:13:41.339040 kademlia.py:236] Cannot get 25 nodes as RoutingTable contains only 15 nodes                                                                                                       │····················
MASTER: W0401 11:13:49.541757 master.py:124] [R] abort syncing due to forking at super old block 21726 << 26398    
```

**Comment by ninjaahhh** [comment] 2019-04-02 00:45
@Bambarello just to clarify, when you say "2.4.4 node", do you actually mean [2.5.4](https://github.com/QuarkChain/pyquarkchain/releases/tag/v2.5.4)?

**Comment by Bambarello** [comment] 2019-04-02 10:48
Yes, sorry - the latest build we have now

**Comment by ninjaahhh** [comment] 2019-05-05 09:47
seems to be data inconsistent issue. close since lots of fixes have been merged

**Closed by ninjaahhh** 2019-05-05 09:47 UTC
